success = "{} successfully published to the network"
invalid_tx_size = "transaction exceeded max size"
invalid_tx_fields = "{}"
serialize_failed = "SERIALIZED_FAILED: {}"
send_failed = "Could not send transaction"
