# Internode filters
DEFAULT_FILTER = '0'
WITNESS_MASTERNODE_FILTER = '1'
DELEGATE_DELEGATE_FILTER = '2'
MASTERNODE_DELEGATE_FILTER = '3'
WITNESS_DELEGATE_FILTER = '4'
CATCHUP_MN_DN_FILTER = '5'
TRANSACTION_FILTER = '6'

# IPC Filters
STATESYNC_FILTER = '7'
