find . -name '*-ReactorIPC-*' -delete
find . -name '*TestableProcess-*' -delete
find . -name '*TestableProcess_*' -delete
find . -name '*-ReactorIPC-*' -delete
find . -name 'LProcess-*' -delete
find . -name '*tmp_exec_code_*' -delete
find . -name '*mptest-ipc-*' -delete
find . -name '*-ipc-sock*' -delete
find . -name 'fsock' -delete
find . -name '.coverage' -delete
find . -name '*docker-compose.yml' -delete
find . -name '*Dockerfile' -delete
